Repository RocketFanOrg/RocketFanApp, pull requests merged in 2019-05, with the labels that each got.

#47 Add LaunchCell for displaying launch info
  RocketFan.xcodeproj/project.pbxproj
  RocketFan/Feature/Launches/All/LaunchCell.swift
  RocketFan/Feature/Launches/All/LaunchCell.xib
Labels: enhancement

#50 Add YouTubeViewController
  RocketFan.xcodeproj/project.pbxproj
  RocketFan/Feature/Launches/Details/YouTubeViewController.swift
  RocketFan/Feature/Launches/Details/YouTubeViewController.xib
Labels: enhancement

#51 Issue49
  RocketFan/App/Models/Launch.swift
  RocketFan/Resources/Data/Roadster.json
  RocketFan/Resources/Data/apiinfo.json
  RocketFan/Resources/Data/capsule.json
  RocketFan/Resources/Data/company.json
  RocketFan/Resources/Data/core.json
  RocketFan/Resources/Data/dragon.json
  RocketFan/Resources/Data/history.json
  RocketFan/Resources/Data/landpad.json
  RocketFan/Resources/Data/launches.json
  RocketFan/Resources/Data/launchpad.json
  RocketFan/Resources/Data/mission.json
  RocketFan/Resources/Data/payload.json
  RocketFan/Resources/Data/rocket.json
  RocketFan/Resources/Data/ship.json
  RocketFanTests/Models/PayloadTests.swift
Labels: bug

#53 Add DateFormatter extension
  RocketFan.xcodeproj/project.pbxproj
  RocketFan/Extensions/DateFormatter+Extensions.swift
  RocketFanTests/Extensions/DateFormatterExtensionsTests.swift
Labels: enhancement

#54 Create a model initialiser helper file
  RocketFan.xcodeproj/project.pbxproj
  RocketFan/App/Models/Launch.swift
  RocketFanTests/Helpers/ModelInitialisers.swift
Labels: tooling

#55 Feature/launches
  RocketFan.xcodeproj/project.pbxproj
  RocketFan/Extensions/UIView+Extensions.swift
  RocketFan/Extensions/UIViewController+Extensions.swift
  RocketFan/Feature/Launches/All/LaunchCell.swift
  RocketFan/Feature/Launches/All/LaunchTableViewController.swift
  RocketFan/Feature/Launches/All/LaunchTableViewController.xib
  RocketFan/Feature/Launches/All/LaunchTableViewDataSource.swift
  RocketFan/Feature/Launches/All/LaunchesViewController.swift
  RocketFan/Feature/Launches/LaunchCellViewModel.swift
  RocketFan/Feature/Launches/Shared/LaunchesRepository.swift
  RocketFan/Feature/Shared/ViewControllers/ContentStateViewController.swift
  RocketFan/Protocols/Reusable.swift
  RocketFanTests/Feature/Launches/LaunchCellViewModelTests.swift
  RocketFanTests/Helpers/ModelInitialisers.swift
Labels: enhancement

#56 LaunchCell implementation
  RocketFan/Feature/Launches/All/LaunchCell.swift
Labels: enhancement

#57 Feature/launches
  RocketFan/Feature/Launches/All/LaunchCell.xib
  RocketFan/Feature/Launches/All/LaunchTableViewController.swift
  RocketFan/Feature/Launches/All/LaunchTableViewDataSource.swift
  RocketFan/Feature/Launches/All/LaunchesViewController.swift
  RocketFan/Protocols/Reusable.swift
Labels: enhancement

#58 Added SearchEngine for finding launches and tests
  RocketFan.xcodeproj/project.pbxproj
  RocketFan/Feature/Launches/All/SearchEngine.swift
  RocketFanTests/Feature/Launches/SearchEngineTests.swift
Labels: enhancement

#59 Added LaunchesViewModel
  RocketFan.xcodeproj/project.pbxproj
  RocketFan/Feature/Launches/All/LaunchesViewController.swift
  RocketFan/Feature/Launches/All/LaunchesViewModel.swift
  RocketFan/Feature/Launches/Shared/LaunchesDependencyContainer.swift
  RocketFan/Feature/Launches/Shared/LaunchesRepository.swift
  RocketFan/Feature/Launches/Shared/LaunchesRepositoryProtocol.swift
  RocketFan/Protocols/Repository.swift
  RocketFanTests/Feature/Launches/LaunchesViewModelTests.swift
  RocketFanTests/Feature/Launches/Mocks/MockLaunchesRepository.swift
Labels: enhancement

#60 Add date formatting to LaunchDetailsViewModel
  RocketFan/Extensions/DateFormatter+Extensions.swift
  RocketFan/Feature/Launches/Details/LaunchDetailsViewModel.swift
  RocketFanTests/Feature/Launches/LaunchDetailsViewModelTests.swift
Labels: enhancement

#61 Add LaunchDetailsViewController
  RocketFan.xcodeproj/project.pbxproj
  RocketFan/Feature/Launches/Details/LaunchDetailsViewController.swift
  RocketFan/Feature/Launches/Details/LaunchDetailsViewController.xib
Labels: enhancement
