Repository RocketFanOrg/RocketFanApp, pull requests merged in 2019-03, with the labels that each got.

#2 [WIP] SwiftFormat and SwiftLint rules
  .swiftformat
Labels: enhancement, tooling

#3 Feature/issue1
  Dangerfile
  Gemfile
  Gemfile.lock
Labels: enhancement, tooling

#4 Create style files
  .swiftformat
  RocketFan.xcodeproj/project.pbxproj
  RocketFanApp.swiftformat
  swiftlint.yml
Labels: enhancement, tooling

#7 Allow User config settings
  .gitignore
  Config/Base.xcconfig
  Config/User.xcconfig
  README.md
  RocketFan.xcodeproj/project.pbxproj
  RocketFan.xcodeproj/xcshareddata/xcschemes/RocketFan.xcscheme
Labels: tooling

#9 [WIP] SpaceXAPI
  RocketFan.xcodeproj/project.pbxproj
  RocketFan.xcodeproj/xcshareddata/xcschemes/RocketFan.xcscheme
  SpaceXAPI/Info.plist
  SpaceXAPI/SpaceXAPI.h
  SpaceXAPITests/Info.plist
  SpaceXAPITests/SpaceXAPITests.swift
Labels: wip

#10 Add SwiftLint and SwiftFormat to Dangerfile
  .swiftformat
  .swiftlint.yml
  Dangerfile
  Gemfile
  Gemfile.lock
  RocketFan.xcodeproj/project.pbxproj
Labels: tooling

#12 Show lint errors inline
  Dangerfile
Labels: tooling

#13 Generate code coverage
  RocketFan.xcodeproj/xcshareddata/xcschemes/RocketFan.xcscheme
Labels: tooling

#14 Add SpaceXAPI and task tests
  RocketFan.xcodeproj/project.pbxproj
  SpaceXAPI/Endpoints/Endpoint.swift
  SpaceXAPI/NetworkSessionProtocol.swift
  SpaceXAPI/Result.swift
  SpaceXAPI/SpaceXAPI+Error.swift
  SpaceXAPI/SpaceXAPI+Options.swift
  SpaceXAPI/SpaceXAPI.swift
  SpaceXAPITests/SpaceXAPIOptionsTests.swift
  SpaceXAPITests/SpaceXAPITests.swift
  SpaceXAPITests/TestHelpers/TestHelpers.swift
  SpaceXAPITests/TestHelpers/XCTestCase+assert.swift
Labels: enhancement

#17 Change SpaceXAPI target
  RocketFan.xcodeproj/project.pbxproj
  SpaceXAPI/SpaceXAPI.h
Labels: bug

#16 Mark endpoints as public
  SpaceXAPI/Endpoints/Capsules.swift
  SpaceXAPI/Endpoints/Cores.swift
  SpaceXAPI/Endpoints/Dragons.swift
  SpaceXAPI/Endpoints/History.swift
  SpaceXAPI/Endpoints/Info.swift
  SpaceXAPI/Endpoints/LandingPads.swift
  SpaceXAPI/Endpoints/LaunchPads.swift
  SpaceXAPI/Endpoints/Launches.swift
  SpaceXAPI/Endpoints/Missions.swift
  SpaceXAPI/Endpoints/Payloads.swift
  SpaceXAPI/Endpoints/Roadster.swift
  SpaceXAPI/Endpoints/Rockets.swift
  SpaceXAPI/Endpoints/Ships.swift
  SpaceXAPI/SpaceXAPI+Error.swift
Labels: bug

#19 Ignore tests files from coverage
  codecov.yml
Labels: bug, tooling

#24 Don't sign frameworks at build times
  RocketFan.xcodeproj/project.pbxproj
  RocketFan.xcodeproj/xcshareddata/xcschemes/RocketFan.xcscheme
Labels: tooling
