Repository RocketFanOrg/RocketFanApp, pull requests merged in 2019-04, with the labels that each got.

#32 Stop codecov comments
  codecov.yml
Labels: tooling

#31 Compare SpaceXAPITests query items using Sets
  SpaceXAPITests/SpaceXAPITests.swift
Labels: bug, tooling

#37 Add Settings model
  .gitignore
  RocketFan.xcodeproj/project.pbxproj
  RocketFan/Utilities/Settings.swift
  RocketFanTests/.swiftlint.yml
  RocketFanTests/Utilities/SettingsTests.swift
Labels: enhancement

#41 Migrated to Swift implementation of Result type
  RocketFan.xcodeproj/project.pbxproj
  SpaceXAPI/Result.swift
  SpaceXAPI/SpaceXAPI.swift
  SpaceXAPITests/SpaceXAPITests.swift
  SpaceXAPITests/TestHelpers/XCTestCase+assert.swift
Labels: enhancement

#42 Bump SWIFT_VERSION build setting to 5.0
  RocketFan.xcodeproj/project.pbxproj
Labels: tooling

#46 Feature/launches
  RocketFan.xcodeproj/project.pbxproj
  RocketFan/App/AppDelegate.swift
  RocketFan/App/MainTabBarController.swift
  RocketFan/Dependency Containers/DependencyContainer.swift
  RocketFan/Extensions/UIViewController+Extensions.swift
  RocketFan/Feature/Launches/All/LaunchesViewController.swift
  RocketFan/Feature/Launches/Shared/LaunchesCoordinator.swift
  RocketFan/Feature/Launches/Shared/LaunchesDependencyContainer.swift
  RocketFan/Feature/Launches/Shared/LaunchesRepository.swift
  RocketFan/Feature/Launches/Shared/LaunchesViewControllerFactory.swift
  RocketFan/Feature/Shared/ViewControllers/ContentStateViewController.swift
  RocketFan/Feature/Shared/ViewControllers/LoadingViewController/LoadingViewController.swift
  RocketFan/Feature/Shared/ViewControllers/LoadingViewController/LoadingViewController.xib
Labels: approved
