Repository RocketFanOrg/RocketFanApp, pull requests merged in 2020-06, with the labels that each got.

#101 #100 - Added Kingfisher using SPM
  RocketFan.xcodeproj/project.pbxproj
  RocketFan.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  RocketFan.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: enhancement

#103 #102 - Added mission patches in launches row
  RocketFan/App/Models/Links.swift
  RocketFan/Feature/Launches/All/LaunchRow.swift
  RocketFan/Feature/Launches/LaunchCellViewModel.swift
  RocketFanTests/Feature/Launches/LaunchCellViewModelTests.swift
Labels: enhancement

#104 feature: add app icons and launchScreen image
  RocketFan/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  RocketFan/Resources/Assets.xcassets/AppIcon.appiconset/Icon-60@2x-1.png
  RocketFan/Resources/Assets.xcassets/AppIcon.appiconset/Icon-60@2x.png
  RocketFan/Resources/Assets.xcassets/AppIcon.appiconset/Icon-60@3x.png
  RocketFan/Resources/Assets.xcassets/AppIcon.appiconset/Icon-Notification@3x.png
  RocketFan/Resources/Assets.xcassets/AppIcon.appiconset/Icon-Small-40.png
  RocketFan/Resources/Assets.xcassets/AppIcon.appiconset/Icon-Small-40@2x.png
  RocketFan/Resources/Assets.xcassets/AppIcon.appiconset/Icon-Small@2x.png
  RocketFan/Resources/Assets.xcassets/AppIcon.appiconset/Icon-Small@3x.png
  RocketFan/Resources/Assets.xcassets/AppIcon.appiconset/iTunesArtwork@2x.png
  RocketFan/Resources/Assets.xcassets/launchScreen.imageset/Contents.json
  RocketFan/Resources/Assets.xcassets/launchScreen.imageset/launchScreen.pdf
  RocketFan/Storyboards/Base.lproj/LaunchScreen.storyboard
Labels: approved, enhancement

#107 add icons assets and define RFIcons enum
  RocketFan.xcodeproj/project.pbxproj
  RocketFan/Feature/Shared/Views/RFIcons.swift
  RocketFan/Resources/Icons.xcassets/Contents.json
  RocketFan/Resources/Icons.xcassets/apoapsis.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/apoapsis.imageset/apoapsis.pdf
  RocketFan/Resources/Icons.xcassets/block.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/block.imageset/block.pdf
  RocketFan/Resources/Icons.xcassets/customers.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/customers.imageset/customers.pdf
  RocketFan/Resources/Icons.xcassets/date.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/date.imageset/date.pdf
  RocketFan/Resources/Icons.xcassets/flightNumber.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/flightNumber.imageset/flightNumber.pdf
  RocketFan/Resources/Icons.xcassets/images.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/images.imageset/images.pdf
  RocketFan/Resources/Icons.xcassets/inclanation.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/inclanation.imageset/inclanation.pdf
  RocketFan/Resources/Icons.xcassets/landingSuccess.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/landingSuccess.imageset/landingSuccess.pdf
  RocketFan/Resources/Icons.xcassets/landingType.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/landingType.imageset/landingType.pdf
  RocketFan/Resources/Icons.xcassets/landingVehicle.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/landingVehicle.imageset/landingVehicle.pdf
  RocketFan/Resources/Icons.xcassets/launchPad.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/launchPad.imageset/launchPad.pdf
  RocketFan/Resources/Icons.xcassets/load.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/load.imageset/load.pdf
  RocketFan/Resources/Icons.xcassets/longitude.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/longitude.imageset/longitude.pdf
  RocketFan/Resources/Icons.xcassets/manufacturer.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/manufacturer.imageset/manufacturer.pdf
  RocketFan/Resources/Icons.xcassets/nationality.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/nationality.imageset/nationality.pdf
  RocketFan/Resources/Icons.xcassets/orbit.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/orbit.imageset/orbit.pdf
  RocketFan/Resources/Icons.xcassets/periapsis.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/periapsis.imageset/periapsis.pdf
  RocketFan/Resources/Icons.xcassets/reused.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/reused.imageset/reused.pdf
  RocketFan/Resources/Icons.xcassets/rocket.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/rocket.imageset/rocket.pdf
  RocketFan/Resources/Icons.xcassets/serial.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/serial.imageset/serial.pdf
  RocketFan/Resources/Icons.xcassets/type.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/type.imageset/type.pdf
  RocketFan/Resources/Icons.xcassets/watchVideo.imageset/Contents.json
  RocketFan/Resources/Icons.xcassets/watchVideo.imageset/watchVideo.pdf
  RocketFanTests/Models/ImageTests.swift
Labels: enhancement

#108 Update Danger gem
  Gemfile.lock
Labels: tooling
